// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckSetup():Promise<boolean>;

export function GetStatus():Promise<Record<string, any>>;

export function Ping(arg1:string):Promise<void>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<void>;
