// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckSetup() {
  return window['go']['main']['App']['CheckSetup']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function Ping(arg1) {
  return window['go']['main']['App']['Ping'](arg1);
}

export function Register(arg1, arg2) {
  return window['go']['main']['App']['Register'](arg1, arg2);
}
